In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
data=pd.read_csv("Housing.csv")

In [32]:
data


price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [33]:
data.info

<bound method DataFrame.info of         price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no

In [34]:
data.describe

<bound method NDFrame.describe of         price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       

In [35]:
data.shape

(545, 13)

In [36]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [37]:
data.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [38]:
data.isna().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [39]:
data.dtypes

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [40]:
data['furnishingstatus'].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [41]:
data['prefarea'].unique()

array(['yes', 'no'], dtype=object)

In [42]:
data['airconditioning'].unique()

array(['yes', 'no'], dtype=object)

In [43]:
data['mainroad'].unique()

array(['yes', 'no'], dtype=object)

In [44]:
from sklearn import preprocessing

In [45]:
label_encoder=preprocessing.LabelEncoder()

In [46]:
data['furnishingstatus']=label_encoder.fit_transform(data['furnishingstatus'])
data['mainroad']=label_encoder.fit_transform(data['mainroad'])
data['guestroom']=label_encoder.fit_transform(data['guestroom'])
data['basement']=label_encoder.fit_transform(data['basement'])
data['hotwaterheating']=label_encoder.fit_transform(data['hotwaterheating'])
data['airconditioning']=label_encoder.fit_transform(data['airconditioning'])
data['prefarea']=label_encoder.fit_transform(data['prefarea'])

In [47]:
data['furnishingstatus']

0      0
1      0
2      1
3      0
4      0
      ..
540    2
541    1
542    2
543    0
544    2
Name: furnishingstatus, Length: 545, dtype: int32

In [48]:
data

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1   
1           0                0                1        3         0   
2           1                0                0        2         1   
3           1                0                1        3         1   
4           1                0                1        2         0   
..        ...              ...              ...      ...       ...   
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

     furnishingstatus  
0                   0  
1                   0  
2                   1  
3                   0  
4                   0  
..                ...  
540                 2  
541                 1  
542                 2  
543                 0  
544                 2  

[545 rows x 13 columns]

In [49]:
data.columns
y=data['price']
y

x=data.drop('price',axis=1)
x

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0    7420         4          2        3         1          0         0   
1    8960         4          4        4         1          0         0   
2    9960         3          2        2         1          0         1   
3    7500         4          2        2         1          0         1   
4    7420         4          1        2         1          1         1   
..    ...       ...        ...      ...       ...        ...       ...   
540  3000         2          1        1         1          0         1   
541  2400         3          1        1         0          0         0   
542  3620         2          1        1         1          0         0   
543  2910         3          1        1         0          0         0   
544  3850         3          1        2         1          0         0   

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
0                  0                1        2         1                 0  
1                  0                1        3         0                 0  
2                  0                0        2         1                 1  
3                  0                1        3         1                 0  
4                  0                1        2         0                 0  
..               ...              ...      ...       ...               ...  
540                0                0        2         0                 2  
541                0                0        0         0                 1  
542                0                0        0         0                 2  
543                0                0        0         0                 0  
544                0                0        0         0                 2  

[545 rows x 12 columns]

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [52]:
len(x_train),len(x_test),len(y_train),len(y_test)
# y_train.shape

(381, 164, 381, 164)

In [53]:
x_test

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
138   5000         3          1        3         1          0         0   
113   9620         3          1        1         1          0         1   
26    6000         3          2        4         1          1         1   
177   6050         3          1        1         1          0         1   
368   5640         2          1        1         0          0         0   
..     ...       ...        ...      ...       ...        ...       ...   
299   7000         3          1        1         1          0         0   
270   4500         3          2        3         1          0         0   
111   8372         3          1        3         1          0         0   
186  11410         2          1        2         1          0         0   
372   3180         3          1        2         0          0         1   

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
138                0                1        0         0                 1  
113                0                0        2         1                 0  
26                 0                1        0         1                 1  
177                0                0        0         1                 1  
368                0                0        0         0                 1  
..               ...              ...      ...       ...               ...  
299                0                0        3         0                 0  
270                1                0        1         0                 0  
111                0                1        2         0                 2  
186                0                0        0         1                 0  
372                0                0        0         0                 1  

[164 rows x 12 columns]

In [54]:

from sklearn import linear_model
lr=linear_model.LinearRegression()
model = lr.fit(x_train,y_train)
prediction=model.predict(x_test)
prediction

array([ 5012758.28788892,  6015035.04071571,  8279375.20855971,
        4485574.82527676,  3049927.13734756,  6870099.66456598,
        6625016.59803015, 10751121.23119304,  6677610.63534496,
        3552494.24508362,  3934449.65558962,  4842885.70607253,
        3029597.02846921,  2730469.74133975,  6753313.29798174,
        4872587.35235999,  3979859.73768778,  3889781.53291455,
        6910224.39658509,  3685894.82305091,  5650141.51974355,
        3469903.70039682,  2749558.40587861,  7363758.56309527,
        3171495.38999819,  2709511.47227629,  3182425.65511823,
        4893332.23936633,  2359894.52440891,  3484767.06866948,
        6818679.55803926,  2256862.22972647,  5099666.92825686,
        3313555.9211117 ,  5585895.46087263,  4667802.54811509,
        7708203.93387214,  3764856.49509953,  2818164.52901833,
        5969967.24326318,  7502767.91120229,  6293964.72433601,
        4379587.35642349,  5825592.84016346,  5448984.00200745,
        6481726.32215744,  3077498.93760

In [55]:
model.predict([[3000,2,1,2,1,0,0,0,0,0,0,1]])

c:\Users\hisha\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3224603.79989902])

In [56]:
model.predict([[3820,2,1,2,1,0,0,0,0,0,0,1]])

c:\Users\hisha\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3427533.47394603])

In [57]:
model.score(x_test,y_test)


0.6362693640730706

In [58]:
model.score(x_train,y_train)

0.6864791088424589